---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    app: kafka-broker-1
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    name: kafka-broker-1
  type: NodePort

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka-deployment-1
spec:
  serviceName: kafka1
  replicas: 1
  selector:
    matchLabels:
      name: kafka-broker-1
  template:
    metadata:
      name: kafka-broker-1
      labels:
        name: kafka-broker-1
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_CREATE_TOPICS
          value: "test-topic:1:1:compact"
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "5555"
        - name: KAFKA_CLEANUP_POLICY
          value: "compact"
        volumeMounts:
          - name: kafka-data
            mountPath: "/kafka/kafka-logs"
  volumeClaimTemplates:
      - metadata:
          name: kafka-data
        spec:
          accessModes: ["ReadWriteMany"]
          storageClassName: azurefile-csi-premium
          resources:
            requests:
              storage: 30Gi