kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper-deployment-1
spec:
  serviceName: zoo1
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-1
  template:
    metadata:
      name: zookeeper-1
      labels:
        name: zookeeper-1
    spec:
      containers:
      - name: zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
#        - name: ZOOKEEPER_SERVER_2
#          value: zoo2
#        - name: ZOOKEEPER_SERVER_3
#          value: zoo3
        volumeMounts:
          - name: zoo-data
            mountPath: "/var/lib/zookeeper"
  volumeClaimTemplates:
      - metadata:
          name: zoo-data
        spec:
          accessModes: ["ReadWriteMany"]
          storageClassName: azurefile-csi-premium
          resources:
            requests:
              storage: 30Gi 
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    name: zookeeper-1